//Names: Brian Liebe (bliebe1) & Jonathan Chang (jchang66)

all: generator prog4

generator: generator.cpp
	g++ generator.cpp -o generator -Wall -Wextra

prog4: prog4.cpp
	g++ prog4.cpp -o prog4 -Wall -Wextra

clean:
	rm -f generator prog4
